[build]
  command = "npm run build"
  publish = ".next"
  environment = { NEXT_TELEMETRY_DISABLED = "1", NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_server"
  status = 200